### ISSUE TITLE
change

### ISSUE THREAD

**Issue by ale-php** [saekort/datamapper#4]
I am programmer php and found some things in datamapper leaving the User
  arrested as the relationships they contain _id joins us , I made a change on
the line in 1716 removing the _id was better to work , would the datamapper git
for me to do a fork and put my improvements

hugs

att Alexandre E. Souza

**Comment by saekort** [comment]
Sorry for not getting back to you yet, it has been busy.

Your english is a bit difficult to interpret for me, but I think you mean that Datamapper has the suffix for foreign and join keys always be '_id'? This is something that has been bugging me as well, yet removing suffixes alltogether does not seem to me to be the best solution to this problem. It would make users have to always define the name of a (foreign)key.

What would probably be a better way to go is to have the _id be a config parameter that is on '_id' by default, but changeable on application and on model basis. I will make a issue and we shall see when we get to it. :)

**Comment by ale-php** [comment]
okay, I was using a translator .
